// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3DLSzJNaNkNw9DCMGD51oOXYjHfYJXag',
    appId: '1:535483176560:web:393318ce00890fe17506b5',
    messagingSenderId: '535483176560',
    projectId: 'sssmnc-2457d',
    authDomain: 'sssmnc-2457d.firebaseapp.com',
    storageBucket: 'sssmnc-2457d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr5n25Rg17BtjX6jXCud-ST-lzbOfNEWk',
    appId: '1:535483176560:android:d043e01b018b1e767506b5',
    messagingSenderId: '535483176560',
    projectId: 'sssmnc-2457d',
    storageBucket: 'sssmnc-2457d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE7eIjWRV8vXtcmI1JQ7i-ALRu7j16OVU',
    appId: '1:535483176560:ios:0b8498e2ca9286f57506b5',
    messagingSenderId: '535483176560',
    projectId: 'sssmnc-2457d',
    storageBucket: 'sssmnc-2457d.firebasestorage.app',
    iosBundleId: 'com.example.templeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE7eIjWRV8vXtcmI1JQ7i-ALRu7j16OVU',
    appId: '1:535483176560:ios:0b8498e2ca9286f57506b5',
    messagingSenderId: '535483176560',
    projectId: 'sssmnc-2457d',
    storageBucket: 'sssmnc-2457d.firebasestorage.app',
    iosBundleId: 'com.example.templeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3DLSzJNaNkNw9DCMGD51oOXYjHfYJXag',
    appId: '1:535483176560:web:1a733b07a01e28e87506b5',
    messagingSenderId: '535483176560',
    projectId: 'sssmnc-2457d',
    authDomain: 'sssmnc-2457d.firebaseapp.com',
    storageBucket: 'sssmnc-2457d.firebasestorage.app',
  );
}
